	
	
CREATE TABLE IF NOT EXISTS Artist (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(60) NOT NULL,
	DESCRIPTION TEXT);	
	
CREATE TABLE IF NOT EXISTS Genre (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(60) NOT NULL,
	DESCRIPTION TEXT);
	
CREATE TABLE IF NOT EXISTS GenreArtist (
	id serial PRIMARY KEY,
	Artist_id integer NOT NULL REFERENCES Artist(id),
	Genre_id integer NOT NULL REFERENCES Genre(id)
	);

CREATE TABLE IF NOT EXISTS Album (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(60) NOT NULL,
	Year INTEGER NOT NULL,
	DESCRIPTION TEXT);

CREATE TABLE IF NOT EXISTS AlbumArtist (
	id serial PRIMARY KEY,
	Album_id integer NOT NULL REFERENCES Album(id),
	Artist_id integer NOT NULL REFERENCES Artist(id)
	);

CREATE TABLE IF NOT EXISTS Track (
	ID SERIAL PRIMARY KEY,
	Album_id integer NOT NULL REFERENCES Album(id),
	NAME VARCHAR(60) NOT NULL,
	Duration float NOT NULL,
	DESCRIPTION TEXT);



CREATE TABLE IF NOT EXISTS Compilation (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(60) NOT NULL,
	Year INTEGER NOT NULL,
	DESCRIPTION TEXT);



CREATE TABLE IF NOT EXISTS CompilationTrack (
	id serial PRIMARY KEY,
	Compilation_id integer NOT NULL REFERENCES Compilation(id),
	Track_id integer NOT NULL REFERENCES Track(id)
	);